services:
  server:
    image: typesense/typesense:${TYPESENSE_VERSION}
    entrypoint: sh -c "/opt/typesense-server --log-dir /var/log --enable-access-logging --data-dir /data --api-key=${ADMIN_API_KEY} --enable-cors"
    ports:
      - "1290:${PORT}"
    volumes:
      - poptape_search_data:/data
    networks:
      - poptape

networks:
  poptape:
    external: true

volumes:
  poptape_search_data:
    name: poptape_search_data
